import React from 'react'
import Head from 'next/head'
import { TITLE } from '@/src/constant'

interface WrapperProps {
  children: React.ReactNode
  title?: string
}

const Wrapper = (props: WrapperProps) => {
  const { title = TITLE.DEFAULT_TITLE, children } = props
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  )
}

export default Wrapper
